# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cf5c5da943e862cca6f2d343ecf0a53"
name = "storerx"
application_url = "https://storerx.fly.dev"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_content,write_content,read_themes"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://storerx.fly.dev/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
